# Generated by Django 4.2.7 on 2023-11-11 11:53

from django.db import migrations, models

import requests

def forwards_func(apps, schema_editor):
    OtherPost = apps.get_model("helper", "OtherPost")
    db_alias = schema_editor.connection.alias

    r = requests.get("https://newsapi.org/v2/top-headlines?country=us&category=science&apiKey=6f407712397e49659ca673564e51906d")
    data = r.json()

    for i in data['articles']:
        if i['title'] == '[Removed]':
            continue
        else:
            OtherPost.objects.using(db_alias).bulk_create(
                [
                    OtherPost(title=i['title'], sphere='science', source=i['source']['name'], url=i['url'], content=i['content'], date_posted=i['publishedAt'], author=i['author']),
                ]
            )

class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpost',
            name='url',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otherpost',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='otherpost',
            name='date_posted',
            field=models.CharField(max_length=100),
        ),
    ]
