# Generated by Django 4.2.7 on 2023-11-12 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helper', '0006_alter_liked_author_alter_likedcomments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
